### PR TITLE
Composer.json and phpunit changes

### PR DESCRIPTION
**Pull request by braxter**
- Composer updates
  - Require php >= 5.4 since traits and short array syntax are used.
   - Remove duplicate requirements from require-dev
   - Remove 'reference' from composer.json - Versions should be tagged or use the version property (tagging is helpful with [packagist](https://packagist.org/packages/bandwidth/iris) as well)

- phpunit Updates
   - phpunit will be installed in /bin directory with composer
   - Update composer to require phpunit
   - update documents to show new path

### CODE REVIEW

**Comment by dtolb** [comment]
@braxter Thanks for opening! I'll review tomorrow.

**Comment by braxter** [comment]
I thought about things a bit more. 

[guzzlehttp/guzzle](https://packagist.org/packages/guzzlehttp/guzzle)     requires: ```"php": ">=5.5"```

 It would probably make sense to just bump the composer.json to that same version to reduce confusion.

**Comment by dtolb** [comment]
do you want to make that change real quick ?

**Comment by braxter** [comment]
composer.json has been updated.

**Comment by braxter** [comment]
One last thing. You will need create a tag for tag v0.0.11 on master, then things should be usable with composer `minimum-stability` set to stable.

**Comment by dtolb** [comment]
@braxter since this hadn't had any tags previously I'm going to move this to [v1](https://packagist.org/packages/bandwidth/iris#v1.0.0)

**Pull request merged**
