### PR TITLE
Update LidbModel.php

### PR DESCRIPTION
**Pull request by samsnelling**
This PR satisfies the data models in your tests (which are incorrect), the GET response, and the POST body parsing of the production API.

The data returned from the production endpoint looks like:
```
<?xml version="1.0" encoding="UTF-8"?>
<LidbOrderResponse>
   <LidbOrder>
      <OrderCreateDate>2016-06-08T13:17:42.701Z</OrderCreateDate>
      <AccountId>x</AccountId>
      <CreatedByUser>x</CreatedByUser>
      <OrderId>x-x-x-x-x</OrderId>
      <LastModifiedDate>2016-06-08T13:17:42.701Z</LastModifiedDate>
      <ProcessingStatus>RECEIVED</ProcessingStatus>
      <LidbTnGroups>
         <LidbTnGroup>
            <TelephoneNumbers>
               <TelephoneNumber>888</TelephoneNumber>
            </TelephoneNumbers>
            <SubscriberInformation>TEST</SubscriberInformation>
            <UseType>BUSINESS</UseType>
            <Visibility>PUBLIC</Visibility>
         </LidbTnGroup>
      </LidbTnGroups>
      <ErrorList />
   </LidbOrder>
</LidbOrderResponse>
```

### CODE REVIEW

**Comment by samsnelling** [comment]
This should resolve #2

**Comment by samsnelling** [comment]
@dtolb please review

**Comment by dtolb** [comment]
@samsnelling we chatted on talkus... But basically: we found you are the only user using this, so if you would like to go with your original change and update the tests to pass we can merge that

**Comment by dtolb** [comment]
@samsnelling Did you all figure out which way you want to take the SDK?

**Comment by samsnelling** [comment]
@dtolb I believe that this PR is the way to go. After some testing, my original PR breaks the `GET` method whereas this PR doesn't break anything with the production API.

**Pull request merged**
